### ISSUE TITLE
kubearmor automatic stopped watchalerts problem

### ISSUE THREAD

**Issue by Jaideep1997** [kubearmor/KubeArmor#1331]
## Bug Report

**Unexpected behavior**

karmor logs
local port to be used for port forwarding kubearmor-relay-6fddb8865b-bh2fk: 32813 
Created a gRPC client (localhost:32813)
Checked the liveness of the gRPC server
Started to watch alerts
== Alert / 2023-07-26 11:45:49.815282 ==
ClusterName: default
HostName: ip-192-168-65-235
NamespaceName: nginx
PodName: nginx-deployment-68f7f96974-9dz8m
Labels: app=nginx
ContainerName: nginx
ContainerID: 20575b9e764f40001c080a96c135f3e75f8545c8fa7b802cc1ae6dac47f97501
ContainerImage: docker.io/library/nginx:latest@sha256:08bc36ad52474e528cc1ea3426b5e3f4bad8a130318e3140d6cfe29c8892c7ef
Type: MatchedPolicy
PolicyName: ksp-group-1-proc-path-block
Severity: 1
Source: /usr/bin/bash
Resource: /usr/bin/apt update
Operation: Process
Action: Block
Data: syscall=SYS_EXECVE
Enforcer: BPFLSM
Result: Permission denied
HostPID: 24617
HostPPID: 24568
Owner: map[Name:nginx-deployment Namespace:nginx Ref:Deployment]
PID: 69
PPID: 63
ParentProcessName: /usr/bin/bash
ProcessName: /usr/bin/apt
releasing grpc client
Stopped WatchAlerts

**Screenshots**

**Comment by nyrahul** [comment]
This usually happens due to connection breakages experienced by internal port-forwarding done by `karmor logs` command.
Note that `karmor logs` is not a solution to be used for long-standing logs/telemetry/alerts pull. The right thing to do would be to either stream the logs to elf, prometheus etc. [Check this](https://github.com/kubearmor/kubearmor-dashboards) for ref.
