### ISSUE TITLE
Automate the KubeArmor Performance Benchmarking Data Process

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubearmor/KubeArmor#1468]
Create a pod for doing benchmarking for https://github.com/kubearmor/KubeArmor/issues/1152

https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-Performance-Benchmarking-Data

**Comment by ShubhamTatvamasi** [comment]
@Shreyas220 @DelusionalOptimist, please share the current scripts for benchmarking.

**Comment by DelusionalOptimist** [comment]
Hey @ShubhamTatvamasi the earlier benchmarks were done by generating some load upon sock-shop using apache-bench tool. The latency and other data for the sock-shop was reported by apache-bench and the performance of KubeArmor daemon, installed on the node running the frontend-service, using `kubectl top`.

Here is how I used it and hacked a bit around with pipes and shell utils to output in a CSV compatible format.
```bash
watch -n 1 -d  'echo "`date +%H:%M:%S`,`kubectl top pods -n kubearmor --sort-by=memory -l kubearmor-app=kubearmor | tail -n 1 | tr -s " " | cut -d " " --output-delimiter "," -f2,3`" | tee -a perf.csv'
```

However this was makeshift because we didn't have a way to disable telemetry for a namespace, thus we didn't use any tools (to keep our benchmarks clean). However we can disable visibility for a namespace now. I think prom and grafana should be used now, as you suggested earlier.

**Comment by DelusionalOptimist** [comment]
Will be taken up as part of GSoC. Ref - https://github.com/kubearmor/KubeArmor/issues/1669
