### ISSUE TITLE
Failed to pull KubeArmor images

### ISSUE THREAD

**Issue by r0binak** [kubearmor/KubeArmor#1536]
## Bug Report

When I try to install KubeArmor Operator following the official documentation from Getting Started section, I get an error Failed to pull images. Problematic images:

- kubearmor/kubearmor-controller
- kubearmor/kubearmor-relay-server
- kubearmor/kubearmor-snitch:latest
- kubearmor/kubearmor-init:stable
- kubearmor/kubearmor

**General Information**

- Kubeadm
- 5.15.0-76-generic
- kubernetes version 1.24.17

**To Reproduce**
```bash
helm repo add kubearmor https://kubearmor.github.io/charts
helm repo update kubearmor
helm upgrade --install kubearmor-operator kubearmor/kubearmor-operator -n kubearmor --create-namespace
kubectl apply -f https://raw.githubusercontent.com/kubearmor/KubeArmor/main/pkg/KubeArmorOperator/config/samples/sample-config.yml
```

**Expected behavior**

I expect KubeArmor to install without errors

**Screenshots**

<img width="1609" alt="Снимок экрана 2023-12-06 в 18 22 54" src="https://github.com/kubearmor/KubeArmor/assets/80983900/fa2dba86-dc0a-48c1-8382-22ff63cdca4c">

**Comment by nyrahul** [comment]
Hey @r0binak , this seems to be an issue with your local k8s cluster. Check if you have a admission controller operating in the context that is denying the image pull.

**Comment by r0binak** [comment]
> Hey @r0binak , this seems to be an issue with your local k8s cluster. Check if you have a admission controller operating in the context that is denying the image pull.

Probably not. Cos any image have been already downloaded

**Comment by daemon1024** [comment]
Please check https://github.com/containerd/containerd/issues/8438

It's an issue between the local cluster and registry interaction. The thread mentions it could also be due to rate limiting by the docker hub API. I don't think the kubearmor maintainers team can help here.

One possible solution is to manually copy the images to your own registry and trying from there.

Closing the issue, Let us know if you are still facing this.
