### ISSUE TITLE
testcase #9 is always failed in minikube

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#213]
With minikube, all test cases except for test case 9 are passed.
However, test case 9 is always failed; thus, we need to check the reason and fix this issue.

**Comment by oneiro-naut** [comment]
@nam-jaehyun I believe it will be fixed if runc corner case is handled. I am working on it. I noticed one thing a while ago when enabling hostlogs that sometimes even when the actual result of an event was Permission Denied the alerts were giving us "No such File or Directory". But I think that is fixed now. I will check to make sure if it's not related to this test failing. What I did was trying to access `/etc/shadows/` on the host to generate HostLog and see.

**Comment by oneiro-naut** [comment]
@nam-jaehyun The policy used in test 9 is not being enforced properly. In the policy we have this line:
https://github.com/kubearmor/KubeArmor/blob/3387c60ff2bbef0dcd0cca10d25968e9ae1ee071/examples/multiubuntu/security-policies/ksp-ubuntu-4-file-path-readonly-allow.yaml#L16
This means we allow binaries in /bin to be executed but I am getting permission denied and can't even run /bin/bash.
The corresponding apparmor rules emitted for this policy is:
```
  /bin/* ix,
  /dev/tty rw,
  /etc/passwd r,
  /etc/nsswitch.conf r,
  /secret.txt rw,
  /credentials/password r,
```
We have the line `/bin/* ix,` here which should allow the binaries to run. But we get permission denied. Since bash can't run this line fails as well:
https://github.com/kubearmor/KubeArmor/blob/3387c60ff2bbef0dcd0cca10d25968e9ae1ee071/examples/multiubuntu/security-policies/ksp-ubuntu-4-file-path-readonly-allow.yaml#L28
Because in test we use bash to run the echo command.
Something similar happens with test 8 and its policy contains a similar line and it fails as well(I am unable to run /bin/bash):
https://github.com/kubearmor/KubeArmor/blob/3387c60ff2bbef0dcd0cca10d25968e9ae1ee071/examples/multiubuntu/security-policies/ksp-ubuntu-3-proc-dir-allow.yaml#L14
It emits a similar apparmor rule:
```
## == Managed by KubeArmor == ##

#include <tunables/global>

profile kubearmor-multiubuntu-ubuntu-3-container flags=(attach_disconnected,mediate_deleted) {
  ## == PRE START == ##
  #include <abstractions/base>
  umount,
  network,
  capability,
  ## == PRE END == ##

  ## == POLICY START == ##
  /bin/* ix,
  /credentials/{*,**} rw,
  ## == POLICY END == ##

  ## == POST START == ##
  /lib/x86_64-linux-gnu/{*,**} r,

  deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
  deny @{PROC}/sysrq-trigger rwklx,
  deny @{PROC}/mem rwklx,
  deny @{PROC}/kmem rwklx,
  deny @{PROC}/kcore rwklx,

  deny mount,

  deny /sys/[^f]*/** wklx,
  deny /sys/f[^s]*/** wklx,
  deny /sys/fs/[^c]*/** wklx,
  deny /sys/fs/c[^g]*/** wklx,
  deny /sys/fs/cg[^r]*/** wklx,
  deny /sys/firmware/efi/efivars/** rwklx,
  deny /sys/kernel/security/** rwklx,
  ## == POST END == ##
}
```
Shouldn't this allow the binaries to run? Also why are we using ix and not x(I think this inherit prefix is the issue)? This also explains why we never got SYS_OPEN and SYS_OPENAT for the runc corner case the reason being it never even happened. And so if this is solved we won't need any extra cases to handle runc corner case.

**Comment by oneiro-naut** [comment]
@nam-jaehyun. Deploting kubearmor on minikube gives me this error which I think is related to ebpf support on minikube.
```
➜  multiubuntu git:(master) kubectl logs kubearmor-tl7rt -n kube-system
2021-07-26 10:37:14.203579	INFO	Started to serve gRPC-based log feeds
2021-07-26 10:37:14.204514	INFO	Initializing an eBPF program
modprobe: module kheaders not found in modules.dep
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module)
2021-07-26 10:37:14.205910	ERROR	Failed to initialize the system monitor
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
	/usr/src/KubeArmor/KubeArmor/log/logger.go:94
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Err
	/usr/src/KubeArmor/KubeArmor/feeder/feeder.go:470
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:352
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:61
runtime.main
	/usr/local/go/src/runtime/proc.go:204
2021-07-26 10:37:14.205961	INFO	Stopped the system monitor
2021-07-26 10:37:14.205966	INFO	Terminated the KubeArmor
chdir(/lib/modules/4.19.182/build): No such file or directory
2021-07-26 10:37:16.206286	INFO	Terminated the gRPC service
2021-07-26 10:37:16.206417	INFO	Stopped the log feeder
```
My minikube version is: v1.20.0
```
$ uname -a
Linux minikube 4.19.182 #1 SMP Wed May 5 21:20:39 UTC 2021 x86_64 GNU/Linux
```
I found this issue which might be related to this https://github.com/kubernetes/minikube/issues/8556. I think I will need to have minikube with newer kernel versions in it(v5.x i guess). Can you please tell me the minikube version which you used?

**Comment by nam-jaehyun** [comment]
@oneiro-naut did you install kernel-headers too?
In my case, I used this script to start Minikube.
https://github.com/kubearmor/KubeArmor/blob/master/contribution/minikube/minikube-start.sh

**Comment by oneiro-naut** [comment]
@nam-jaehyun I didn't use the script earlier now I am using it. Thanks.
