### ISSUE TITLE
ownerOnly doesn't work in Ubuntu 18.04

### ISSUE THREAD

**Issue by nam-jaehyun** [kubearmor/KubeArmor#300]
## Bug Report

**General Information**

- Environment description

Checked this issue from 'kubearmor-dev' (vagrant, ubuntu 18.04)

- Kernel version

4.15.0-151-generic

- Orchestration system version in use

Kubernetes version: 1.21.4

**To Reproduce**

Assume that KubeArmor is already running.

1. Apply wordpress-mysql

```
$ kubectl apply -f KubeArmor/examples/wordpress-mysql
```

2. Apply test.yaml

```
$ vi test.yaml

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wordpress-block-config
  namespace: wordpress-mysql
spec:
  severity: 10
  selector:
    matchLabels:
      app: wordpress
  file:
    matchPaths:
    - path: /var/www/html/wp-config.php
      ownerOnly: true

      # http://[NodeIP]:30080
      # cat /var/www/html/wp-config.php
 
  action:
    Block

$ kubectl apply -f test.yaml
```

3. Get into the WordPress pod and run the following commands

```
$ kubectl -n wordpress-mysql exec -it [WordPress pod] -- bash

root@wordpress-dbcd8b97b-pwfmc:/var/www/html# ls -l wp-config.php
-rw-r--r-- 1 www-data www-data 3151 Aug 27 10:21 wp-config.php
```

Here, the owner of wp-config.php is 'www-data', not 'root'.

- Expectation

```
root@wordpress-dbcd8b97b-pwfmc:/var/www/html# cat /var/www/html/wp-config.php
cat: wp-config.php: Permission denied

<Alert>

http://[NodeIP]:30080 -> can access the Wordpress blog
```

- Reality

```
root@wordpress-dbcd8b97b-pwfmc:/var/www/html# cat /var/www/html/wp-config.php
...content...

<No Alert>
```

**Expected behavior**

'ownerOnly' means that the owner (Linux permission system) of the file can only execute the file; otherwise, all should be blocked. However, it seems that the 'ownerOnly' option doesn't work on Ubuntu 18.04.

This option worked previously. I guess that this option may not work according to AppArmor versions.

**Comment by oneiro-naut** [comment]
@nam-jaehyun The policy used here uses action `Block` which should be `Allow` because in a way we are whitelisting here(with Allow it will just allow the owner to access the specified file and all other files would denied for all other users). Also if there is already some Block policy applied to the same container the profile will have a `file,` rule and therefore there will be similar conflicts. As a possible solution we might create sub profiles for ownerOnly just as we create for fromSource to avoid such conflict.

**Comment by daemon1024** [comment]
Summarising a few points here:
- this is an issue irrespective of apparmor or ubuntu version
- this is an issue only for ownerOnly read/write rules, exec rules work as intended
- the issue is due to giving `file` rule when we have a whitelisting ownerOnly policy

Proposed Solution:
- Adding a `deny other` rule along with `owner`.

```sh
  deny other /foo rw,
  owner /foo rw,
```

I have tested it against the test case mentioned in the issue ( with allow policy not block )

Few concerns regarding using the `other` keyword:

Other is not officially supported and there's a proposal to change the keyword to something more relevant to what it does but that said it will keep working regardless and they don't plan to break this functionality

( quoting jjohansen from #apparmor on IRC ):

> so as said 'other' exists but it has never been officially supported
the syntax proposal is to change it to either !owner OR owner!=@{user}
what is meant by 'other' is not very clear

> also, while unofficial and 'other' will likely never be an official part of the profile language. As long as there isn't a need to break it, it will continue to work
just in profiles in the future you will see the alternate form
