### ISSUE TITLE
documentation needed for adding system tests

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#533]
Tasks:
- [x] Explain current structure for [system tests](https://github.com/kubearmor/KubeArmor/tree/main/tests)
- [x] How to add new test?
- [x] How to check coverage?
- [x] How to integrate newly added test in the overall system test so that it can run as part of CI/GH-action?

Expected Output:
- [x] document explaining above with sample test

**Comment by DARK-art108** [comment]
Can I work on this issue? @nyrahul

**Comment by nyrahul** [comment]
> Can I work on this issue? @nyrahul

That will be great! Let us know if you have any questions.

**Comment by subhamgcon** [comment]
Hey @nyrahul, Is this issue still open for work? If yes, can i work on it?

**Comment by daemon1024** [comment]
@subhamgcon Sure go ahead 😄 Thanks for the interest. Let us know if you have any questions.

**Comment by subhamgcon** [comment]
Hey @daemon1024, This is first time writing a documentation on System tests. Can you please share my examples with me so that i can get an idea on how to proceed?

**Comment by daemon1024** [comment]
@subhamgcon 
I recently added a test case as part of https://github.com/kubearmor/KubeArmor/commit/dbfb5cc4d76824911b7da104f3b89c724b1136ae
Ignore the changes in script files.
A basic workflow of adding a test includes
- A policy YAML file - against which tests are to be performed
- A set of commands, which will be executed against the policy
	- Each cmd file includes, command to be executed, whether the command should pass or fail and what would be the expected telemetry event generated

This should summaries things.
You can try out adding a test case yourself in order to better understand the process and document accordingly.

Hope it helps ✌🏽

**Comment by exitflynn** [comment]
Hi! 
If this issue is not being worked on right now, I would love to do so! :cowboy_hat_face:

**Comment by Ankurk99** [comment]
Hey @exitflynn, sorry for a late response. Are you still available to work on this issue?

**Comment by shivangshandilya** [comment]
I would like to work on this issue if possible and this would be my first time writing a system test documentation so if you could guide me along the way that would be helpful too. Regards

**Comment by SD-13** [comment]
@Ankurk99 @daemon1024 I would like to give it a try. Can you please assign me?
