### ISSUE TITLE
KubeArmor contribution guide needs to be updated without Vagrant

### ISSUE THREAD

**Issue by asifalix** [kubearmor/KubeArmor#601]
## Feature Request

**Short Description**

KubeArmor contribution guide could have instructions that do not include Vagrant

KubeArmor contribution guide should have a contribution guide for developers on a Linux environment without using Vagrant. This needs to be updated..

**Comment by asifalix** [comment]
Further we might want to add granular instructions on how to configure this and run in pure vm workloads.

**Comment by nyrahul** [comment]
@asifalix, the [development guide](https://github.com/kubearmor/KubeArmor/blob/main/contribution/development_guide.md) has option 2 that allows the developer to setup dev env directly on Linux host without using vagrant. However, we do not recommend using it. We recommend using vagrant based setup since it takes care of setting up all the relevant build softwares. With vagrant we have seen much less dev env setup issues and almost all of the developers are currently using vagrant based dev env.
