### ISSUE TITLE
support for CRIO container runtime

### ISSUE THREAD

**Issue by nyrahul** [kubearmor/KubeArmor#666]
## Feature Request

Kubearmor currently supports docker, and containerd container runtimes for k8s.
There are several k8s engine (for e.g. [OpenShift](https://docs.openshift.com/container-platform/3.11/crio/crio_runtime.html)) that use [CRIO](https://cri-o.io/).

Kubearmor connects to container-runtime to get the mount-namespace and other details (for e.g., container image details etc). These details are used subsequently in the telemetry/log enrichment. For e.g.,
1. to check if the process event is in context to the given container/namespace.
2. to check what is the container image id for the event that is generated

The aim here is to look into containerd implementation in kubearmor and map it to CRIO as well.

Tasks:
- [ ] design points
- [ ] validate policy enforcement with CRIO
- [ ] validate alerts/telemetry with CRIO
- [ ] testing with local k8s env with CRIO

**Comment by DelusionalOptimist** [comment]
@nyrahul @nam-jaehyun @daemon1024 I took a look into how support for other CRIs has been implemented and tried to draw parallels.
I think the [client](https://github.com/cri-o/cri-o/blob/main/internal/client/client.go) provided by CRIO doesn't give all the info that we need about the containers. For e.g. it doesn't provide the container spec (like containerd) through which we can get the apparmor profile. So, meanwhile I'm taking a looking into how we can get it, do you folks have any other suggestions/concerns?

Also, can one of you please assign this to me? Thanks.

**Comment by nam-jaehyun** [comment]
@DelusionalOptimist can you explain what values we cannot get from CRIO?

**Comment by DelusionalOptimist** [comment]
@nam-jaehyun I was comparing the container structs defined by containerd and cri-o and saw that [containerd](https://github.com/containerd/containerd/blob/eb39aace3cadc4e01ef18b0e3706edf3b5249b6c/api/services/containers/v1/containers.pb.go#L42) provides some more fields over [cri-o](https://github.com/cri-o/cri-o/blob/db76322414a7888c7642b707e07dbb9905aa969f/pkg/types/types.go#L8) which may affect how we implement this.
On a quick look I only realized the  `spec` field which we use for getting the Apparmor profile associated with a conatiner.

**Comment by DelusionalOptimist** [comment]
I think the best (and only) option here would be to use the [cri-api](https://github.com/kubernetes/cri-api).
We can get basic data needed for a [Container](https://github.com/kubearmor/KubeArmor/blob/7410c1c91ead25bb28e15ed628ceb908d30ca897/KubeArmor/types/types.go#L19) from [cri-api's container](https://github.com/kubernetes/cri-api/blob/1c90a6f7abe8f5b7331c95960a5106c9876a9e4f/pkg/apis/runtime/v1alpha2/api.pb.go#L4886), and its metadata, annotations and labels.
Apparmor profile from [container status](https://github.com/kubernetes/cri-api/blob/1c90a6f7abe8f5b7331c95960a5106c9876a9e4f/pkg/apis/runtime/v1alpha2/api.pb.go#L5111) or [container config](https://github.com/kubernetes/cri-api/blob/1c90a6f7abe8f5b7331c95960a5106c9876a9e4f/pkg/apis/runtime/v1alpha2/api.pb.go#L4137) (verified through crictl). And the approach thereafter remains similar.

Regarding usage of cri-api for working with other container runtimes - I think it will work out fine and I've tried them out with `crictl` but I propose we first support cri-o and later extend it for others.

If this sounds good, lmk so that I may start working on the implementation.

**Comment by nyrahul** [comment]
If cri-api can work, that will be the best thing to happen. But please have a look at [this file](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/containerdHandler.go) to check what information we need from container runtime.

**Comment by DelusionalOptimist** [comment]
Yes @nyrahul, I had taken it into consideration as well.
