### ISSUE TITLE
Ignore empty policy

### ISSUE THREAD

**Issue by Ankurk99** [kubearmor/KubeArmor#769]
## Bug Report

**Environment**
KubeArmor running in host	mode

**General Information**
Add check to KubeArmor to ignore accepting blank policies. If a policy ends with "---" KubeArmor currently takes it as an additional empty policy.
It will have issues for eg: If we run KubeArmor in containerized mode then it will create an empty apparmor profile (with name kubearmor_) for that empty policy.

**Expected behavior**
KubeArmor should ignore blank policies (policy yaml ending with "---").

**Comment by daemon1024** [comment]
I think we should validate the entire policy, not just limit this check to blanks. Like if the policy has the required fields or not and conforms to our CRD.

**Comment by slayer321** [comment]
Hey @daemon1024 , I did like to work on this issue. 
Also can you point me to the folder were all the codes related to policy resides .

**Comment by Ankurk99** [comment]
The policy matching logic is implemented in feeder/policyMatcher.go

**Comment by Ankurk99** [comment]
Hello @slayer321, did you got the time to look into it?

**Comment by slayer321** [comment]
Not yet @Ankurk99 , but I'm going to look into issue this weekend

**Comment by Chinwendu20** [comment]
Hi @slayer321 are you still working on this? I am a first timer and I am looking for good first issues to work on

**Comment by Ankurk99** [comment]
Hi @Chinwendu20, glad to see your interest. There are multiple good-first issues looking for help in KubeArmor. You may take a look at them https://github.com/kubearmor/KubeArmor/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

**Comment by daemon1024** [comment]
The fix in client would only be a partial fix, the CLI tool is just one of the possible client, but the gRPC server for KubeArmor is exposed and any one could leverage the gRPC endpoint to send policies. We should have validation of policy values inside our code as well. WDYT?

**Comment by Ankurk99** [comment]
Yes, that makes sense, I missed exposing KubeArmor API point. Thanks for pointing. 
Hey @Chinwendu20, I am assigning you the issue. Feel free to contact us on KubeArmor

**Comment by Chinwendu20** [comment]
Okay thanks a lot. I would get right on it

**Comment by Ankurk99** [comment]
Hey @Chinwendu20! Do we have any update on this issue? Feel free to ask for any pointers.

**Comment by Chinwendu20** [comment]
Hello @Ankurk99 thanks again for assigning this issue to me. I went through the file you suggested, policymatcher.go and the function for updateandparsecontainer but I still could not figure out where to make the change. I did not hit you up with follow questions because I was trying to figure it out by myself. I was going through the codebase to better understand where to include the check. Reading up about custom kubernetes controller and CRD, I felt I would have a better grasp of what was going on in the codebase. I even went through the codebase of the karmor cli to better understand the journey the manifest file would go through before reaching the server. I am still in this process although admittedly I have been interrupted by other engagements. Attempting to create a PR for this issue has offered me the opportunity to delve deeper into k8. I would still like to continue in this process, if I can be afforded one more week to attempt this issue, I would be grateful. Also I would be glad to get any pointer from you at this point.

**Comment by Chinwendu20** [comment]
I believe that I have made great progress in this issue, I have been able to trace to find out the function that receives the policyeventdata in kubeamor. I can make a check there. I should create PR for review soon.

**Comment by daemon1024** [comment]
Great @Chinwendu20, Many thanks for the continued effort towards this and really happy that you are making substantial progress. Looking forward to the PR 😁

**Comment by Ankurk99** [comment]
@Chinwendu20 Sorry I missed your last message. Glad to know that you have made some progress!

**Comment by Chinwendu20** [comment]
Thank you all for your patience with me. @daemon1024 you mentioned this. Could you please tell me what fields you feel are the required fields? the metadata field?

> I think we should validate the entire policy, not just limit this check to blanks. Like if the policy has the required fields or not and conforms to our CRD.

**Comment by Chinwendu20** [comment]
I have submitted the PR
